### ISSUE TITLE
Wiki pages review

### ISSUE THREAD

**Issue by bcdasilv** [addisonmartin/share-the-food#96]
I reviewed the environment instructions on the wiki pages. Here a few comments:
   * What's the Ruby appropriate version? I had Ruby 2.3.7 already installed but wasn't sure if that would be enough or I had to update to 2.6. Would versions above 2.6 be ok? Be more explicit there.
   * In my computer, I tried to install rails without rbenv and it didn't work (you said rbenv is optional). Then I skipped rails and followed the next steps. I stopped at "bundle install" because it seems to require rbenv. Then, I installed rbenv successfully, then I tried to install rails again and it worked. Is rbenv or another package manager really optional?
   * Ruby versions are very tricky. In my mac I had 2.3.7 (it comes already installed in macOS) then I decided to upgrade and installed the most recent one (2.6.3) via homebrew. The OS was still recognizing the previous installation (2.3.7). I had to spend some time researching how to fix that. 
   * There's no explicit instruction there to tell the developer to run postgresql before building the database. I know this is kind of obvious, but it's worth adding an instruction there before the "bundle exec rake ..." commands. Before those commands I ran "postgres -D /usr/local/var/postgres" (but there other ways to run postgresql)
   * After struggling with different ruby versions, I realized I should have installed RVM. I know it's not required, but might be helpful especially in my case that I had to deal with multiple ruby versions.
   * I haven't executed the other sections (i.e. test and deployment) but they look good and I think you covered well. I think it's worth adding a note on each wiki instruction page to open an issue if someone sees a mistake in the instructions (can we add a link to direct to the issue creation page?).

**Comment by addisonmartin** [comment]
- I mention the Ruby version in the configuration section, but I've added it to the Setting up Development Environment because you're right you need to know exactly what Ruby version to install.
- I removed mentioning the version manager as optional, and just say to install a language version manager. It will be easier in the long run as the Ruby version for the project updates.
- Added an instruction to start the postgresql database on your local machine.
- Added a mention to open a new issue in each wiki section.

Thank you!!
